/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import exceptions.NotInTheSystemYestException;

import java.awt.Dimension;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import utils.InputTestsStaticClass;

/**
 *
 * @author Aviad
 */
@SuppressWarnings("serial")
public class addFlightTicketToFlightOrder extends javax.swing.JInternalFrame  {
    //***************************************** Variables *********************************************
    /**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private MyDesktopPane myDesk;
    /**Flg field*/
    int flg = 0;
    //**************************************** Constructor ********************************************
    /**
     * Creates new form addFlightTicketToFlightOrder
     * @param view
     * @param myDesk
     */
    public addFlightTicketToFlightOrder(ViewLogic view, MyDesktopPane myDesk) {
        this.view = view;
        this.myDesk = myDesk;
        setTitle("Add Flight Ticket To Flight Order"); //the title of the frame
        Dimension desktopSize = myDesk.getSize();   // the size of the desktopPane
        initComponents();
        setLocation(((desktopSize.width-this.getSize().width) / 2) , ((desktopSize.height-this.getSize().height) / 2));    // centering the frame on screen
        txtSeatNumber.setText("0");
        txtRowNumber.setText("0");
        txtFee.setText("0.0 $");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbFlightNumber = new javax.swing.JComboBox();
        cbOrderNumber = new javax.swing.JComboBox();
        cbPassportNumber = new javax.swing.JComboBox();
        txtSeatNumber = new javax.swing.JTextField();
        txtRowNumber = new javax.swing.JTextField();
        cbClassType = new javax.swing.JComboBox();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnChoose = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFee = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-ticket-xxl.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Flight Number:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Order Number:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel3.setText("Passport Number:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel4.setText("Your Seat Number:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Your Row Number:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Class Type:");

        cbFlightNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbFlightNumber.setModel(new DefaultComboBoxModel(view.getFlights().keySet().toArray()));

        cbOrderNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbOrderNumber.setModel(new DefaultComboBoxModel(view.getAllOrders()));

        cbPassportNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbPassportNumber.setModel(new DefaultComboBoxModel(view.getCustomers().keySet().toArray()));

        txtSeatNumber.setEditable(false);
        txtSeatNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtSeatNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSeatNumber.setForeground(new java.awt.Color(51, 51, 51));

        txtRowNumber.setEditable(false);
        txtRowNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtRowNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtRowNumber.setForeground(new java.awt.Color(51, 51, 51));

        cbClassType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbClassType.setModel(new DefaultComboBoxModel(utils.E_ClassType.values()));
        cbClassType.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbClassType.setEnabled(false);

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setText("OK");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnChoose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChoose.setText("Choose");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("Choose Seat:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("Ticket Fee:");

        txtFee.setEditable(false);
        txtFee.setBackground(new java.awt.Color(204, 204, 204));
        txtFee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtFee.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRowNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbFlightNumber, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbOrderNumber, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbPassportNumber, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(txtFee, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbClassType, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPassportNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(btnChoose))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSeatNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRowNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbClassType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       try{
           InputTestsStaticClass.notInSystem(cbFlightNumber, "Flights");
           InputTestsStaticClass.notInSystem(cbPassportNumber, "customers");
           InputTestsStaticClass.notInSystem(cbOrderNumber, "orders");
       
        if(flg == 0 && !txtSeatNumber.getText().equals("0") && !txtRowNumber.getText().equals("0") ){
        view.addFlightTicketToFlightOrder(cbFlightNumber, cbOrderNumber, cbPassportNumber, txtSeatNumber, txtRowNumber, cbClassType, this);
        } else{
        view.sound("/sounds/errorSound.wav");
        int response = JOptionPane.showConfirmDialog(null, "You dident choose a seat! \nwould you like to try again?", "Add Error", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {  // reset fields
            flg = 0;
            cbFlightNumber.setSelectedIndex(0);
            cbOrderNumber.setSelectedIndex(0);
            cbPassportNumber.setSelectedIndex(0);
          } else {
             dispose();
          }
        }
       }catch (NotInTheSystemYestException ex) {
            ex.getStackTrace();
            dispose();
          }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    @SuppressWarnings("deprecation")
	private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        try{
           InputTestsStaticClass.notInSystem(cbFlightNumber, "Flights");
           InputTestsStaticClass.notInSystem(cbPassportNumber, "customers");
           InputTestsStaticClass.notInSystem(cbOrderNumber, "orders");
        if(view.getFlights().get((int)cbFlightNumber.getSelectedItem()).getAirplane().getTotalNumberSeats() <= 200){
        Seats seats = new Seats(null, closable, myDesk, view, (int)cbFlightNumber.getSelectedItem());
        seats.show();
        try{
        if(seats.getFlg() == 0){    
        txtSeatNumber.setText(String.valueOf(seats.getSeat()));
        txtRowNumber.setText(String.valueOf(seats.getRow()));
        cbClassType.setSelectedIndex(seats.getClassType().ordinal());
        txtFee.setText(" "+String.valueOf((int)(view.getFlights().get((int)cbFlightNumber.getSelectedItem()).getFlightCost()*seats.getClassType().getFee()))+" $");
        } else {
            flg = 1;
        }
       }catch (NullPointerException e){
            System.out.printf(e.getMessage());
       }
      } else {
          SeatsOver200 seatsOver200 = new SeatsOver200(null, closable, myDesk, view, (int)cbFlightNumber.getSelectedItem());
        seatsOver200.show();
        try{
        if(seatsOver200.getFlg() == 0){    
        txtSeatNumber.setText(String.valueOf(seatsOver200.getSeat()));
        txtRowNumber.setText(String.valueOf(seatsOver200.getRow()));
        cbClassType.setSelectedIndex(seatsOver200.getClassType().ordinal());
        txtFee.setText(" "+String.valueOf((int)(view.getFlights().get((int)cbFlightNumber.getSelectedItem()).getFlightCost()*seatsOver200.getClassType().getFee()))+" $");
        } else {
            flg = 1;
        }
       }catch (NullPointerException e){
            System.out.printf(e.getMessage());
       }   
        }
        }catch (NotInTheSystemYestException ex) {
            ex.getStackTrace();
            dispose();
          }
    }//GEN-LAST:event_btnChooseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChoose;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbClassType;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbFlightNumber;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbOrderNumber;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbPassportNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtFee;
    private javax.swing.JTextField txtRowNumber;
    private javax.swing.JTextField txtSeatNumber;
    // End of variables declaration//GEN-END:variables
}
