/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import exceptions.NotInTheSystemYestException;
import java.awt.Dimension;

import javax.swing.DefaultComboBoxModel;
import utils.InputTestsStaticClass;

/**
 *
 * @author Aviad
 */
@SuppressWarnings("serial")
public class addPilotOrFlightAttendantToFlight extends javax.swing.JInternalFrame {
    //***************************************** Variables *********************************************
    /**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private MyDesktopPane myDesk;
    //**************************************** Constructor ********************************************
    
    /**
     * Creates new form addPilotOrFlightAttendantToFlight
     * @param view
     * @param myDesk
     */
    public addPilotOrFlightAttendantToFlight(ViewLogic view, MyDesktopPane myDesk) {
        this.view = view;
        this.myDesk = myDesk;
        setTitle("Add Pilot Or FlightAttendant To Flight"); //the title of the frame
        Dimension desktopSize = this.myDesk.getSize();   // the size of the desktopPane
        initComponents();
        setLocation(((desktopSize.width-this.getSize().width) / 2) , ((desktopSize.height-this.getSize().height) / 2));    // centering the frame on screen
        cbPilot.setVisible(false);
        cbFlightAttendant.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        rbPilot = new javax.swing.JRadioButton();
        rbFlightAttendant = new javax.swing.JRadioButton();
        cbPilot = new javax.swing.JComboBox();
        txtEmployee = new javax.swing.JLabel();
        lab = new javax.swing.JLabel();
        cbFlightNumber = new javax.swing.JComboBox();
        cbFlightAttendant = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(102, 102, 102));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rehr_affiliates_main.png"))); // NOI18N

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setText("Ok");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        rbPilot.setBackground(new java.awt.Color(102, 102, 102));
        bg.add(rbPilot);
        rbPilot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbPilot.setForeground(new java.awt.Color(0, 0, 51));
        rbPilot.setText("Pilot");
        rbPilot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPilotActionPerformed(evt);
            }
        });

        rbFlightAttendant.setBackground(new java.awt.Color(102, 102, 102));
        bg.add(rbFlightAttendant);
        rbFlightAttendant.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbFlightAttendant.setForeground(new java.awt.Color(0, 0, 51));
        rbFlightAttendant.setText("FlightAttendant");
        rbFlightAttendant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFlightAttendantActionPerformed(evt);
            }
        });

        cbPilot.setModel(new DefaultComboBoxModel(view.getAllPilots()));

        txtEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmployee.setForeground(new java.awt.Color(0, 0, 51));
        txtEmployee.setText("Employee Number:");

        lab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lab.setForeground(new java.awt.Color(0, 0, 51));
        lab.setText("Flight Number:");

        cbFlightNumber.setModel(new DefaultComboBoxModel(view.getFlights().keySet().toArray())
        );

        cbFlightAttendant.setModel(new DefaultComboBoxModel(view.getAllFlightAttendant()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(rbPilot, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(rbFlightAttendant))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lab, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(cbFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(txtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbFlightAttendant, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbPilot, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPilot)
                    .addComponent(rbFlightAttendant))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmployee)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbFlightAttendant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbPilot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lab))
                    .addComponent(cbFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPilotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPilotActionPerformed
      cbPilot.setVisible(true);
      cbFlightAttendant.setVisible(false);
      try{
           InputTestsStaticClass.notInSystem(cbPilot, "pilots");
        }catch (NotInTheSystemYestException ex) {
            ex.getStackTrace();
            rbPilot.setEnabled(false);
          }
    }//GEN-LAST:event_rbPilotActionPerformed

    private void rbFlightAttendantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFlightAttendantActionPerformed
      cbPilot.setVisible(false);
      cbFlightAttendant.setVisible(true);
      try{
           InputTestsStaticClass.notInSystem(cbFlightAttendant, "flightAttendans");
        }catch (NotInTheSystemYestException ex) {
            ex.getStackTrace();
            rbFlightAttendant.setEnabled(false);
          }
    }//GEN-LAST:event_rbFlightAttendantActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

       view.addPilotOrFlightAttendantToFlight(cbPilot, cbFlightAttendant, cbFlightNumber, rbPilot, rbFlightAttendant, this);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbFlightAttendant;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbFlightNumber;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbPilot;
    private javax.swing.JLabel lab;
    private javax.swing.JRadioButton rbFlightAttendant;
    private javax.swing.JRadioButton rbPilot;
    private javax.swing.JLabel txtEmployee;
    // End of variables declaration//GEN-END:variables
}
