/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import core.FlightOrder;
import core.Order;
import exceptions.NotInTheSystemYestException;

import java.awt.Dimension;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import utils.Constants;
import utils.InputTestsStaticClass;

/**
 *
 * @author Aviad
 */
@SuppressWarnings("serial")
public class CustomerOrders extends javax.swing.JInternalFrame {
    //***************************************** Variables *********************************************
    /**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private MyDesktopPane myDesk;
    /**Order field*/
    String order;
    /**Ticket field*/
    String ticket;
    /**customer field*/
    String customer;
    //**************************************** Constructor ********************************************
    /**
     * Creates new form CustomerOrders
     * @param view
     * @param myDesk
     * @param type
     */
    public CustomerOrders(ViewLogic view, MyDesktopPane myDesk, Constants.typeOfUser type) {
        this.view = view;
        this.myDesk = myDesk;
        setTitle("Update Customer Address"); //the title of the frame
        Dimension desktopSize = this.myDesk.getSize();   // the size of the desktopPane
        initComponents();
        setLocation(((desktopSize.width-this.getSize().width) / 2) , ((desktopSize.height-this.getSize().height) / 2));    // centering the frame on screen
        jScrollPane1.setVisible(false);
        if(type.equals(Constants.typeOfUser.CUSTOMER)){
            cbCustomerPassport.setVisible(false);
            cbCustomerPassport.setSelectedItem(view.getLogInName());
            jScrollPane1.setVisible(true);
            taLogName.setText("  "+view.getLogInName());
            try{
            customer = "Details for customer: " + view.getCustomers().get(view.getLogInName()).getFirstName()+" "+view.getCustomers().get(view.getLogInName()).getLastName()+
                    " Passport Number: "+view.getCustomers().get(view.getLogInName()).getPassportNumber();
            if(!view.getCustomers().get(view.getLogInName()).getOrders().isEmpty()){
                order = "******************************* Orders **********************************\n";
                int i = 1;
                view.sound("/sounds/okSound.wav");  
                for(Order o : view.getCustomers().get(view.getLogInName()).getOrders()){
                    order += i+"."+o.customString()+"\n" ;
                    i++;
                }
                }else{
                     order = "******************************* Orders **********************************\nSorry no orders found\n"; 
                        }
            if(!view.getCustomers().get(view.getLogInName()).getFlightTickets().isEmpty()){
                ticket = "******************************* Tickets **********************************\n";
                int j = 1;
                view.sound("/sounds/okSound.wav");  
                for(FlightOrder.FlightTicket f : view.getCustomers().get(view.getLogInName()).getFlightTickets()){
                    ticket += j+"."+f.theString()+"\n" ;
                    j++;
                }
            }else{
                ticket = "******************************* Tickets **********************************\nSorry no tickets found\n";
            }
                taCustomerOrders.setText(customer+"\n"+order+"\n"+ticket);
            }catch (Exception e){
                view.sound("/sounds/errorSound.wav");
                JOptionPane.showMessageDialog(null, "Sorry this flight details are not available!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbCustomerPassport = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        taLogName = new javax.swing.JTextArea();
        txtCustomerPassport = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taCustomerOrders = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customerdt.png"))); // NOI18N

        cbCustomerPassport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbCustomerPassport.setModel(new DefaultComboBoxModel(view.getCustomers().keySet().toArray()));
        cbCustomerPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCustomerPassportActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        taLogName.setEditable(false);
        taLogName.setColumns(20);
        taLogName.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        taLogName.setRows(5);
        jScrollPane1.setViewportView(taLogName);

        txtCustomerPassport.setBackground(new java.awt.Color(153, 153, 153));
        txtCustomerPassport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerPassport.setForeground(new java.awt.Color(0, 0, 51));
        txtCustomerPassport.setText("Customer Passport:");

        taCustomerOrders.setEditable(false);
        taCustomerOrders.setBackground(new java.awt.Color(102, 102, 102));
        taCustomerOrders.setColumns(20);
        taCustomerOrders.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        taCustomerOrders.setRows(5);
        taCustomerOrders.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Customer Orders And Tickets Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Agency FB", 1, 24), new java.awt.Color(0, 0, 51))); // NOI18N
        jScrollPane2.setViewportView(taCustomerOrders);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(txtCustomerPassport)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCustomerPassport, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(780, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtCustomerPassport))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCustomerPassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(454, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(62, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbCustomerPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCustomerPassportActionPerformed
       try{
        InputTestsStaticClass.notInSystem(cbCustomerPassport, "customers");   
        customer = "Details for customer: " + view.getCustomers().get((String)cbCustomerPassport.getSelectedItem()).getFirstName()+" "
            +view.getCustomers().get((String)cbCustomerPassport.getSelectedItem()).getLastName()+" Passport Number: "+view.getCustomers().get((String)cbCustomerPassport.getSelectedItem()).getPassportNumber();   
        if(!view.getCustomers().get((String)cbCustomerPassport.getSelectedItem()).getOrders().isEmpty()){
                order = "******************************* Orders **********************************\n";
                int i = 1;
                view.sound("/sounds/okSound.wav");  
                for(Order o : view.getCustomers().get((String)cbCustomerPassport.getSelectedItem()).getOrders()){
                    order += i+"."+o.customString()+"\n" ;
                    i++;
                }
                }else{
                     order = "******************************* Orders **********************************\nSorry no orders found\n"; 
                        }
            if(!view.getCustomers().get((String)cbCustomerPassport.getSelectedItem()).getFlightTickets().isEmpty()){
                ticket = "******************************* Tickets **********************************\n";
                int j = 1;
                view.sound("/sounds/okSound.wav");  
                for(FlightOrder.FlightTicket f : view.getCustomers().get((String)cbCustomerPassport.getSelectedItem()).getFlightTickets()){
                    ticket += j+"."+f.theString()+"\n" ;
                    j++;
                }
            }else{
                ticket = "******************************* Tickets **********************************\nSorry no tickets found\n";
            }
                taCustomerOrders.setText(customer+"\n"+order+"\n"+ticket);
       }catch (NotInTheSystemYestException ex) {
            ex.getStackTrace();
            dispose();
       }catch (Exception e){
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Sorry this flight details are not available!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
            }
    }//GEN-LAST:event_cbCustomerPassportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbCustomerPassport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taCustomerOrders;
    private javax.swing.JTextArea taLogName;
    private javax.swing.JLabel txtCustomerPassport;
    // End of variables declaration//GEN-END:variables
}
