/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.Dimension;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Aviad
 */
@SuppressWarnings("serial")
public class employeeOfTheMonth extends javax.swing.JInternalFrame {
    //***************************************** Variables *********************************************
    /**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private MyDesktopPane myDesk;
    //**************************************** Constructor ********************************************
    /**
     * Creates new form employeeOfTheMonth
     * @param view
     * @param myDesk
     */
    public employeeOfTheMonth(ViewLogic view, MyDesktopPane myDesk) {
        this.view = view;
        this.myDesk = myDesk;
        setTitle("Employee Of The Month"); //the title of the frame
        Dimension desktopSize = this.myDesk.getSize();   // the size of the desktopPane
        initComponents();
        setLocation(((desktopSize.width-this.getSize().width) / 2) , ((desktopSize.height-this.getSize().height) / 2));    // centering the frame on screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMonth = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taEmployeeOfTheMonth = new javax.swing.JTextArea();
        cbMonths = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/administrator.png"))); // NOI18N

        txtMonth.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMonth.setForeground(new java.awt.Color(0, 0, 51));
        txtMonth.setText("Choose Month:");

        taEmployeeOfTheMonth.setEditable(false);
        taEmployeeOfTheMonth.setBackground(new java.awt.Color(102, 102, 102));
        taEmployeeOfTheMonth.setColumns(20);
        taEmployeeOfTheMonth.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        taEmployeeOfTheMonth.setRows(5);
        taEmployeeOfTheMonth.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Employee Of The Month ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Agency FB", 1, 24), new java.awt.Color(0, 0, 51))); // NOI18N
        jScrollPane1.setViewportView(taEmployeeOfTheMonth);

        cbMonths.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbMonths.setModel(new DefaultComboBoxModel(utils.E_Months.values()));
        cbMonths.setToolTipText("Choose  month");
        cbMonths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMonthsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtMonth)
                .addGap(18, 18, 18)
                .addComponent(cbMonths, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonth)
                    .addComponent(cbMonths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMonthsActionPerformed
        view.employeeOfTheMonth(cbMonths, taEmployeeOfTheMonth, this);
    }//GEN-LAST:event_cbMonthsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbMonths;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taEmployeeOfTheMonth;
    private javax.swing.JLabel txtMonth;
    // End of variables declaration//GEN-END:variables
}
