/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.Dimension;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aviad
 */
@SuppressWarnings("serial")
public class findTheBestFlightBack extends javax.swing.JInternalFrame {
    //***************************************** Variables *********************************************
    /**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private MyDesktopPane myDesk;
    //**************************************** Constructor ********************************************
    /**
     * Creates new form findTheBestFlightBack
     * @param view
     * @param myDesk
     */
    public findTheBestFlightBack(ViewLogic view, MyDesktopPane myDesk) {
        this.view = view;
        this.myDesk = myDesk;
        setTitle("Find The Best Flight Back"); //the title of the frame
        Dimension desktopSize = this.myDesk.getSize();   // the size of the desktopPane
        initComponents();
        setLocation(((desktopSize.width-this.getSize().width) / 2) , ((desktopSize.height-this.getSize().height) / 2));    // centering the frame on screen
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbFlightNumber = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        taFlight = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taBestFlightBack = new javax.swing.JTextArea();
        btnFind = new javax.swing.JButton();
        vacationDaysSpinner = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plane_travel_flighplane_icon.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Flight Number:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Vacation Days:");

        cbFlightNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbFlightNumber.setModel(new DefaultComboBoxModel(view.getFlights().keySet().toArray()));
        cbFlightNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFlightNumberActionPerformed(evt);
            }
        });

        taFlight.setEditable(false);
        taFlight.setBackground(new java.awt.Color(102, 102, 102));
        taFlight.setColumns(20);
        taFlight.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        taFlight.setRows(5);
        taFlight.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Your Flight:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 0, 51))); // NOI18N
        jScrollPane1.setViewportView(taFlight);

        taBestFlightBack.setEditable(false);
        taBestFlightBack.setBackground(new java.awt.Color(102, 102, 102));
        taBestFlightBack.setColumns(20);
        taBestFlightBack.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        taBestFlightBack.setRows(5);
        taBestFlightBack.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "The Best Flight Back:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 0, 51))); // NOI18N
        jScrollPane2.setViewportView(taBestFlightBack);

        btnFind.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        vacationDaysSpinner.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vacationDaysSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(vacationDaysSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFind)
                        .addGap(0, 494, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cbFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind)
                    .addComponent(vacationDaysSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFlightNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFlightNumberActionPerformed
     try{
        int flightNumber = (Integer)cbFlightNumber.getSelectedItem();
        taFlight.setText(view.getFlights().get(flightNumber).toString());
        }catch (NullPointerException e){
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Sorry no flights found!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
        }
    }//GEN-LAST:event_cbFlightNumberActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        try{
        int vacationDays = (Integer)vacationDaysSpinner.getValue();
        int flightNumber = (Integer)cbFlightNumber.getSelectedItem();
        if(cbFlightNumber.getSelectedItem() == null){
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "You must choose a flight!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
        }else if(vacationDays == 0 ){
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "You must choose vacation days!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
        }else if (view.findTheBestFlightBack(flightNumber, vacationDays).isEmpty()){
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Sorry no flights back was found!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
        }else{
            view.sound("/sounds/okSound.wav");
            taBestFlightBack.setText(view.findTheBestFlightBack(flightNumber, vacationDays).toString());
        }
        }catch (NullPointerException e){
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Sorry no flights back was found!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
        }
    }//GEN-LAST:event_btnFindActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox cbFlightNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taBestFlightBack;
    private javax.swing.JTextArea taFlight;
    private javax.swing.JSpinner vacationDaysSpinner;
    // End of variables declaration//GEN-END:variables
}
