/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import core.Agent;
import core.Employee;

import java.awt.Dimension;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import utils.TableColumnAdjuster;

/**
 *
 * @author Aviad
 */
@SuppressWarnings("serial")
public class getAllSuperAgents extends javax.swing.JInternalFrame {
    //***************************************** Variables *********************************************
    /**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private MyDesktopPane myDesk;
    //**************************************** Constructor ********************************************
    /**
     * Creates new form getAllSuperAgents
     * @param view
     * @param myDesk
     */
    public getAllSuperAgents(ViewLogic view, MyDesktopPane myDesk) {
        this.view = view;
        this.myDesk = myDesk;
        setTitle("All Super Agents"); //the title of the frame
        Dimension desktopSize = myDesk.getSize();   // the size of the desktopPane
        initComponents();
        setLocation(((desktopSize.width-this.getSize().width) / 2) , ((desktopSize.height-this.getSize().height) / 2));    // centering the frame on screen
        updateTables();
    }

    private void updateTables() {
       if(!view.getAllSuperAgents().isEmpty()){
           DefaultTableModel modle = new DefaultTableModel(new String[]{"Employee Type", "Employee Number", "First Name", "Last Name", "Birth Date", "Start Working Date", "Password", "Number Of Orders"}, view.getAllSuperAgents().size());
           tabAllSuperAgents.setModel(modle);
           tabAllSuperAgents.setShowGrid(true);
           view.sound("/sounds/okSound.wav");    
        for(Employee e : view.getAllSuperAgents()){            
            if(e instanceof Agent){
                modle.addRow(new Object[]{e.getClass().getSimpleName(), e.getEmployeeNumber(), e.getFirstName(), e.getLastName(), e.getBirthDate(),e.getStartWorkingDate(), e.getPassword(),((Agent)e).getOrders().size()});
            }
        }
        TableColumnAdjuster tca = new TableColumnAdjuster(tabAllSuperAgents);
        tca.adjustColumns(); 
       }  else {
            view.sound("/sounds/errorSound.wav"); 
            JOptionPane.showMessageDialog(null, "Sorry no Super Agents was found ", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/succeedIcon.png"));
            dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabAllSuperAgents = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/depositphotos_6207720-Super-man-icon.jpg"))); // NOI18N

        tabAllSuperAgents.setBackground(new java.awt.Color(102, 102, 102));
        tabAllSuperAgents.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabAllSuperAgents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Type", "Employee Number", "First Name", "Last Name", "Birth Date", "Start Working Date", "Password", "Number Of Orders"
            }
        ) {
            @SuppressWarnings("rawtypes")
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            @SuppressWarnings("rawtypes")
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabAllSuperAgents.setToolTipText("Press to watch agent details");
        tabAllSuperAgents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabAllSuperAgentsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabAllSuperAgents);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabAllSuperAgentsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabAllSuperAgentsMousePressed
        try{
              Employee employee = view.getEmployees().get(Integer.parseInt(tabAllSuperAgents.getModel().getValueAt(tabAllSuperAgents.getSelectedRow(), 1).toString()));
              
              ShowChoice ev = new ShowChoice(null, closable, myDesk, employee);
              ev.setVisible(true);

          }catch (Exception e){
              view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Sorry this agent details are not available!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
          }
    }//GEN-LAST:event_tabAllSuperAgentsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabAllSuperAgents;
    // End of variables declaration//GEN-END:variables
}
