/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import core.Flight;

import java.awt.Dimension;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import utils.TableColumnAdjuster;

/**
 *
 * @author Aviad
 */
@SuppressWarnings("serial")
public class getAllSummerFlightsSortedByNumberOfStops extends javax.swing.JInternalFrame {
    //***************************************** Variables *********************************************
    /**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private MyDesktopPane myDesk;
    //**************************************** Constructor ********************************************
    /**
     * Creates new form getAllSummerFlightsSortedByNumberOfStops
     * @param view
     * @param myDesk
     */
    public getAllSummerFlightsSortedByNumberOfStops(ViewLogic view, MyDesktopPane myDesk) {
        this.view = view;
        this.myDesk = myDesk;
        setTitle("All Summer Flights"); //the title of the frame
        Dimension desktopSize = myDesk.getSize();   // the size of the desktopPane
        initComponents();
        setLocation(((desktopSize.width-this.getSize().width) / 2) , ((desktopSize.height-this.getSize().height) / 2));    // centering the frame on screen
        updateTables();
    }
    
    
    private void updateTables() {
       if(!view.getAllSummerFlightsSortedByNumberOfStops().isEmpty()){
           DefaultTableModel modle = new DefaultTableModel(new String[]{"Flight Number", "Departure Data And Time", "Arrival Date And Time", "Cost", "Number Of Seats","Source", "Destination" , "Stops"},0);
           tabFlights.setModel(modle);
           tabFlights.setShowGrid(true);
           tabFlights.setColumnSelectionAllowed(true);
        view.sound("/sounds/okSound.wav");    
        for(Flight f : view.getAllSummerFlightsSortedByNumberOfStops()){ 
                modle.addRow(new Object[]{f.getFlightNumber(), f.getFlightDateAndTimeSource(), f.getFlightDateAndTimeDestination(), f.getFlightCost(), f.getAirplane().getTotalNumberSeats(),
                 f.getSource(), f.getDestination(), f.getStops()});  
        }
        TableColumnAdjuster tca = new TableColumnAdjuster(tabFlights);
        tca.adjustColumns(); 
       }  else {
            view.sound("/sounds/errorSound.wav"); 
            JOptionPane.showMessageDialog(null, "Sorry no Flights found ", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/succeedIcon.png"));
            dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tabFlights = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_flights.gif"))); // NOI18N

        tabFlights.setBackground(new java.awt.Color(102, 102, 102));
        tabFlights.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "Departure Data And Time", "Arrival Date And Time", "Flight Cost", "Number Of Seats", "Source", "Destination", "Stops"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabFlights.setToolTipText("Press to watch flight details");
        tabFlights.setColumnSelectionAllowed(true);
        tabFlights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabFlightsMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabFlights);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1062, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabFlightsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabFlightsMousePressed
         try{
            Flight flight = view.getFlights().get(Integer.parseInt(tabFlights.getModel().getValueAt(tabFlights.getSelectedRow(), 0).toString()));
            ShowChoice ev = new ShowChoice(null, closable, this.myDesk ,flight);
            ev.setVisible(true);
            
        }catch (Exception e){
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Sorry this flight details are not available!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
        }
    }//GEN-LAST:event_tabFlightsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabFlights;
    // End of variables declaration//GEN-END:variables
}
