/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import core.Agent;
import core.Branch;

import java.awt.Dimension;
import java.util.HashMap;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aviad
 */
@SuppressWarnings("serial")
public class getBranchesAgentsSortedByRating extends javax.swing.JInternalFrame {
    //***************************************** Variables *********************************************
    /**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private MyDesktopPane myDesk;
    /**models map*/
    private HashMap<String,Branch> models;
    /**agent map*/
    private HashMap<String,Agent> agent;
    /**Selected agent field*/
    private String selectedAgent;
    /**Selected branch field*/
    private String selectedBranch;
    //**************************************** Constructor ********************************************
    /**
     * Creates new form getBranchesAgentsSortedByRating
     * @param view
     * @param myDesk
     */
    @SuppressWarnings({ "rawtypes", "unchecked" })
	public getBranchesAgentsSortedByRating(ViewLogic view, MyDesktopPane myDesk) {
        this.models = new HashMap<String, Branch>();
        this.agent = new HashMap<String,Agent>();
        this.view = view;
        this.myDesk = myDesk;
        setTitle("Branch Agents"); //the title of the frame
        Dimension desktopSize = myDesk.getSize();   // the size of the desktopPane
        initComponents();
        setLocation(((desktopSize.width-this.getSize().width) / 2) , ((desktopSize.height-this.getSize().height) / 2));    // centering the frame on screen
        DefaultListModel modle = new DefaultListModel();
        if(!view.getBranchesAgentsSortedByRating().isEmpty()){
        for(Branch b : this.view.getBranchesAgentsSortedByRating().keySet()){
            modle.addElement("Name: "+b.getbranchName()+" Number: "+b.getbranchNumber());
            models.put("Name: "+b.getbranchName()+" Number: "+b.getbranchNumber(), b);
        }
        BranchList.setModel(modle);
        }else{
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Sorry no branches found!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings("rawtypes")
	private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BranchList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        AgentsList = new javax.swing.JList();
        btnShowAgents = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customers.png"))); // NOI18N

        BranchList.setBackground(new java.awt.Color(102, 102, 102));
        BranchList.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true), "Branches:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Agency FB", 1, 24), new java.awt.Color(0, 0, 51))); // NOI18N
        BranchList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BranchList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        BranchList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BranchListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(BranchList);

        AgentsList.setBackground(new java.awt.Color(102, 102, 102));
        AgentsList.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true), "Branch Agents:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Agency FB", 1, 24), new java.awt.Color(0, 0, 51))); // NOI18N
        AgentsList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AgentsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        AgentsList.setToolTipText("Click to watch agent details");
        AgentsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgentsListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(AgentsList);

        btnShowAgents.setBackground(new java.awt.Color(204, 204, 204));
        btnShowAgents.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnShowAgents.setForeground(new java.awt.Color(0, 0, 51));
        btnShowAgents.setText("Show Potential Customers ==>");
        btnShowAgents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAgentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowAgents)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(btnShowAgents)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings({ "rawtypes", "unchecked" })
	private void btnShowAgentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAgentsActionPerformed
        DefaultListModel modle2 = new DefaultListModel();
        try{  
         selectedBranch = (String)BranchList.getSelectedValue();
         if(BranchList.getSelectedValue() == null){
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "you must choose branch first!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
        }else if(view.getBranchesAgentsSortedByRating().get(models.get(selectedBranch)).isEmpty()){
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Sorry this branch have no agents!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
        }else{
            for(Agent a : view.getBranchesAgentsSortedByRating().get(models.get(selectedBranch))){
                modle2.addElement("Name: "+a.getFirstName()+" "+a.getLastName()+" Number: "+a.getEmployeeNumber());
                agent.put("Name: "+a.getFirstName()+" "+a.getLastName()+" Number: "+a.getEmployeeNumber(),(Agent) a);
            }
            view.sound("/sounds/okSound.wav");
            AgentsList.setModel(modle2);
            }
        }catch (NullPointerException e){
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Failed to find this branch have no agents!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
        }
    }//GEN-LAST:event_btnShowAgentsActionPerformed

    private void AgentsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgentsListMouseClicked
        try{  
            if(agent.containsKey((String)AgentsList.getSelectedValue())){
              selectedAgent = (String)AgentsList.getSelectedValue();
              ShowChoice ev = new ShowChoice(null, closable, myDesk, agent.get(selectedAgent));
              ev.setVisible(true);
            }
          }catch (Exception e){
              view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Sorry this agent details are not available!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
          }
    }//GEN-LAST:event_AgentsListMouseClicked

    @SuppressWarnings({ "unchecked", "rawtypes" })
	private void BranchListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BranchListMousePressed
        AgentsList.setModel(new DefaultListModel());
    }//GEN-LAST:event_BranchListMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    @SuppressWarnings("rawtypes")
	private javax.swing.JList AgentsList;
    @SuppressWarnings("rawtypes")
	private javax.swing.JList BranchList;
    private javax.swing.JButton btnShowAgents;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
