/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import core.Agent;
import core.Customer;

import java.awt.Dimension;
import java.util.HashMap;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Aviad
 */
@SuppressWarnings("serial")
public class getPotentialCustomersForAgents extends javax.swing.JInternalFrame {
    //***************************************** Variables *********************************************
    /**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private MyDesktopPane myDesk;
    /**models map*/
    private HashMap<String,Agent> models;
    /**customer map*/
    private HashMap<String,Customer> customer;
    /**Selected customer field*/
    private String selectedCustomer;
    /**Selected agent field*/
    private String selectedAgent;
    //**************************************** Constructor ********************************************
    /**
     * Creates new form getPotentialCustomersForAgents
     * @param view
     * @param myDesk
     */
    @SuppressWarnings({ "rawtypes", "unchecked" })
	public getPotentialCustomersForAgents(ViewLogic view, MyDesktopPane myDesk) {
        this.models = new HashMap<String, Agent>();
        this.customer = new HashMap<String,Customer>();
        this.view = view;
        this.myDesk = myDesk;
        setTitle("Potential Customers For Agents"); //the title of the frame
        Dimension desktopSize = myDesk.getSize();   // the size of the desktopPane
        initComponents();
        setLocation(((desktopSize.width-this.getSize().width) / 2) , ((desktopSize.height-this.getSize().height) / 2));    // centering the frame on screen
        DefaultListModel modle = new DefaultListModel();
        if(!view.getPotentialCustomersForAgents().isEmpty()){
        for(Agent a : view.getPotentialCustomersForAgents().keySet()){
            modle.addElement("Name: "+a.getFirstName()+" "+a.getLastName()+" Number: "+a.getEmployeeNumber());
            models.put("Name: "+a.getFirstName()+" "+a.getLastName()+" Number: "+a.getEmployeeNumber(), a);
        }
        AgentsList.setModel(modle);
        }else{
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Sorry no agents found!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings("rawtypes")
	private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AgentsList = new javax.swing.JList();
        btnShowCustomer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CustomerList = new javax.swing.JList();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customers_customer_user_male_man_people_light.png"))); // NOI18N

        AgentsList.setBackground(new java.awt.Color(102, 102, 102));
        AgentsList.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true), "Agents:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Agency FB", 1, 24), new java.awt.Color(0, 0, 51))); // NOI18N
        AgentsList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AgentsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        AgentsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AgentsListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(AgentsList);

        btnShowCustomer.setBackground(new java.awt.Color(204, 204, 204));
        btnShowCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnShowCustomer.setForeground(new java.awt.Color(0, 0, 51));
        btnShowCustomer.setText("Show Potential Customers ==>");
        btnShowCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowCustomerActionPerformed(evt);
            }
        });

        CustomerList.setBackground(new java.awt.Color(102, 102, 102));
        CustomerList.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true), "Potential Customers:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Agency FB", 1, 24), new java.awt.Color(0, 0, 51))); // NOI18N
        CustomerList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CustomerList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CustomerList.setToolTipText("Click to watch customer details");
        CustomerList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(CustomerList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(btnShowCustomer)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings({ "rawtypes", "unchecked" })
	private void btnShowCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowCustomerActionPerformed
       DefaultListModel modle2 = new DefaultListModel();
        try{
          selectedAgent = (String)AgentsList.getSelectedValue();
         if(AgentsList.getSelectedValue() == null){
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "you must choose agent first!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
        }else if(view.getPotentialCustomersForAgents().get(models.get(selectedAgent)).isEmpty()){
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Sorry no potential customers for this agent!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
        }else{
        for(Customer c : view.getPotentialCustomersForAgents().get(models.get(selectedAgent))){
            modle2.addElement("Name: "+c.getFirstName()+" "+c.getLastName()+" Number: "+c.getPassportNumber());
            customer.put("Name: "+c.getFirstName()+" "+c.getLastName()+" Number: "+c.getPassportNumber(), c);
        }
        view.sound("/sounds/okSound.wav");
        CustomerList.setModel(modle2);
        }
       }catch (NullPointerException e){
           view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Failed to find this agent Potential customers!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
       }
    }//GEN-LAST:event_btnShowCustomerActionPerformed

    private void CustomerListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerListMouseClicked

            try{  
             if(customer.containsKey((String)CustomerList.getSelectedValue())){
              selectedCustomer = (String)CustomerList.getSelectedValue();
              ShowChoice ev = new ShowChoice(null, closable, myDesk, customer.get(selectedCustomer));
              ev.setVisible(true);
             }
          }catch (Exception e){
              view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Sorry this customer details are not available!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
          }
    }//GEN-LAST:event_CustomerListMouseClicked

    @SuppressWarnings({ "unchecked", "rawtypes" })
	private void AgentsListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgentsListMousePressed
        CustomerList.setModel(new DefaultListModel());
    }//GEN-LAST:event_AgentsListMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    @SuppressWarnings("rawtypes")
	private javax.swing.JList AgentsList;
    @SuppressWarnings("rawtypes")
	private javax.swing.JList CustomerList;
    private javax.swing.JButton btnShowCustomer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
