/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import core.Flight;

import java.awt.Dimension;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import utils.TableColumnAdjuster;

/**
 *
 * @author Aviad
 */
@SuppressWarnings("serial")
public class getTheTopXPopularFlights extends javax.swing.JInternalFrame {
    //***************************************** Variables *********************************************
    /**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private MyDesktopPane myDesk;
    //**************************************** Constructor ********************************************
    /**
     * Creates new form getTheTopXPopularFlights
     * @param view
     * @param myDesk
     */
    public getTheTopXPopularFlights(ViewLogic view, MyDesktopPane myDesk) {
        this.view = view;
        this.myDesk = myDesk;
        setTitle("Top Popular Flights"); //the title of the frame
        Dimension desktopSize = myDesk.getSize();   // the size of the desktopPane
        initComponents();
        setLocation(((desktopSize.width-this.getSize().width) / 2) , ((desktopSize.height-this.getSize().height) / 2));    // centering the frame on screen
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabFlights = new javax.swing.JTable();
        spinNumberOfFlights = new javax.swing.JSpinner();
        btnOk = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_256.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Number Of Flights To Display: ");

        tabFlights.setBackground(new java.awt.Color(102, 102, 102));
        tabFlights.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tabFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "Departure Data And Time", "Arrival Date And Time", "Flight Cost", "Number Of Seats", "Source", "Destination", "Stops"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabFlights.setToolTipText("Press to watch flight details");
        tabFlights.setCellSelectionEnabled(true);
        tabFlights.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabFlightsMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabFlights);

        spinNumberOfFlights.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spinNumberOfFlights.setModel(new javax.swing.SpinnerNumberModel());

        btnOk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOk.setText("OK");
        btnOk.setBorder(null);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(spinNumberOfFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(419, 419, 419))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinNumberOfFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

       if((Integer)spinNumberOfFlights.getValue() == 0){
           view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "You must choose number of flights!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
       }else if(!view.getTheTopXPopularFlights(spinNumberOfFlights).isEmpty()){
           DefaultTableModel modle = new DefaultTableModel(new String[]{"Flight Number", "Departure Data And Time", "Arrival Date And Time", "Cost", "Number Of Seats","Source", "Destination" , "Stops"},0);
           tabFlights.setModel(modle);
           tabFlights.setShowGrid(true);
           tabFlights.setColumnSelectionAllowed(true);
           view.sound("/sounds/okSound.wav");    
        for(Flight f : view.getTheTopXPopularFlights(spinNumberOfFlights)){ 
             modle.addRow(new Object[]{f.getFlightNumber(), f.getFlightDateAndTimeSource(), f.getFlightDateAndTimeDestination(), f.getFlightCost(), f.getAirplane().getTotalNumberSeats(),
                 f.getSource(), f.getDestination(), f.getStops()});                         
        }
        TableColumnAdjuster tca = new TableColumnAdjuster(tabFlights);
        tca.adjustColumns(); 
       }  else {
            view.sound("/sounds/errorSound.wav"); 
            JOptionPane.showMessageDialog(null, "Sorry no Popular Flights found ", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/succeedIcon.png"));
            dispose();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void tabFlightsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabFlightsMousePressed
        try{
            Flight flight = view.getFlights().get(Integer.parseInt(tabFlights.getModel().getValueAt(tabFlights.getSelectedRow(), 0).toString()));
            ShowChoice ev = new ShowChoice(null, closable, this.myDesk ,flight);
            ev.setVisible(true);
            
        }catch (Exception e){
            view.sound("/sounds/errorSound.wav");
            JOptionPane.showMessageDialog(null, "Sorry this flight details are not available!", "Added Message", JOptionPane.PLAIN_MESSAGE, view.icon("/images/symbolError.png"));
        }
    }//GEN-LAST:event_tabFlightsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spinNumberOfFlights;
    private javax.swing.JTable tabFlights;
    // End of variables declaration//GEN-END:variables
}
