/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.Dimension;

/**
 *
 * @author Aviad
 */
@SuppressWarnings("serial")
public class getTheMostProfitableOrder extends javax.swing.JInternalFrame {
    //***************************************** Variables *********************************************
    /**view field*/
    private ViewLogic view;
    /**MyDesktopPane field*/
    private MyDesktopPane myDesk;
    //**************************************** Constructor ********************************************
    /**
     * Creates new form getTheMostProfitableOrder
     * @param view
     * @param myDesk
     */
    public getTheMostProfitableOrder(ViewLogic view, MyDesktopPane myDesk) {
        this.view = view;
        this.myDesk = myDesk;
        setTitle("The Most Profitable Order"); //the title of the frame
        Dimension desktopSize = this.myDesk.getSize();   // the size of the desktopPane
        initComponents();
        setLocation(((desktopSize.width-this.getSize().width) / 2) , ((desktopSize.height-this.getSize().height) / 2));    // centering the frame on screen
        execute();      
    }
  private void execute(){
        this.view.getTheMostProfitableOrder(taMostProfitableOrder, this);
        jScrollPane1.setOpaque(false);  // make the background transparent
        jScrollPane1.getViewport().setOpaque(false);
        taMostProfitableOrder.setOpaque(false); 
        taMostProfitableOrder.setCaretPosition(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taMostProfitableOrder = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pay-icon.gif"))); // NOI18N

        taMostProfitableOrder.setEditable(false);
        taMostProfitableOrder.setBackground(new java.awt.Color(102, 102, 102));
        taMostProfitableOrder.setColumns(20);
        taMostProfitableOrder.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        taMostProfitableOrder.setRows(5);
        taMostProfitableOrder.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "The Most Profitble Order", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Agency FB", 1, 24), new java.awt.Color(0, 0, 51))); // NOI18N
        jScrollPane1.setViewportView(taMostProfitableOrder);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taMostProfitableOrder;
    // End of variables declaration//GEN-END:variables
}
