/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;



import exceptions.LoginFailedException;
import exceptions.MissingFieldsException;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.*;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import utils.*;
import utils.Constants.typeOfUser;



/**
 *
 * @author Aviad
 */
public class LoginFrame extends javax.swing.JFrame {
    
    //***************************************** Variables *********************************************

    /**
    * serial
    */
    private static final long serialVersionUID = 5948973650284115554L;
    /**The user type*/
    private typeOfUser type;
    /**Login approval*/
    private boolean loginApproved = false;
    /**Flag variable*/
    private int flag = 0;
    /**ViewLogic field*/
    private static ViewLogic view;
    
     //***************************************** Constructor *********************************************
         
    /**
     * Creates new form ViewLogic
     * @param viewLogic
     */
    public LoginFrame(ViewLogic viewLogic) { 
         try {
                UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                    e.getMessage();
            try {
                UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                ex.getMessage();
            }
        }
        LoginFrame.view = viewLogic;
        initComponents();
        setVisible(true);
        setResizable(false);
        setSize(528, 476);
        setLocationRelativeTo(null);
        setTitle("Welcome To iFly Company");
        setIcon();
        user.setOpaque(false);
        user.setCaretColor(Color.GRAY);
        passwordField.setOpaque(false);
        passwordField.setCaretColor(Color.GRAY);
        
        }

     //***************************************** Methods *********************************************

    /**
     * return the answer if its ok to enter the system or not 
     * @return loginApproved
     */
    public boolean loginApproved(){
        return loginApproved;
    }
    /**
     * login method 
     */
    public void login() {  
       
       try{ 
            type = view.login(user.getText(), String.valueOf(passwordField.getPassword()));
            loginApproved = true;         // if there is not exception change logivApproved to true
            view.executeDesktopView(type);
            flag++;                       // if the login is OK the flag will increase by one
            dispose();
         } catch (MissingFieldsException | LoginFailedException excep) {           
            excep.getMessage();
         }
    }
    
    /**
     * sound method, will allow to play sound when necessary
     * @param fileName
     */
    public void soundMethod(String fileName) {       // this is the method that handling the sound effect of the program.
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(getClass().getResource(fileName));
            Clip clip = AudioSystem.getClip();
            clip.open(audio);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error Sound File", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * setIcon method, allow to add icon to frame
     */
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/airportIcon.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        logButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(null);

        userLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(204, 204, 204));
        userLabel.setText("User Name:");
        getContentPane().add(userLabel);
        userLabel.setBounds(110, 190, 90, 30);

        passLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        passLabel.setForeground(new java.awt.Color(204, 204, 204));
        passLabel.setText("Password:");
        getContentPane().add(passLabel);
        passLabel.setBounds(110, 240, 90, 30);

        user.setBackground(new java.awt.Color(102, 102, 102));
        user.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        user.setToolTipText("Enter User Name Here");
        user.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userKeyPressed(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(220, 190, 150, 30);

        logButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logButton.setText("LOGIN");
        logButton.setToolTipText("Click here to login");
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logButton);
        logButton.setBounds(140, 320, 90, 30);

        resetButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetButton.setText("RESET");
        resetButton.setToolTipText("Click here to reset fieldes");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton);
        resetButton.setBounds(310, 320, 90, 30);

        passwordField.setBackground(new java.awt.Color(102, 102, 102));
        passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordField.setToolTipText("Enter Password Here");
        passwordField.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        passwordField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordField.setPreferredSize(new java.awt.Dimension(2, 22));
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        getContentPane().add(passwordField);
        passwordField.setBounds(220, 240, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login-pageee.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 60, 320, 80);

        loginJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login_Backgrounddd.png"))); // NOI18N
        getContentPane().add(loginJLabel);
        loginJLabel.setBounds(0, 0, 522, 450);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        user.setText("");
        passwordField.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        view.setLogInName(user.getText());
        login();
        if(flag == Constants.FLAG)           // if the login succeed the sound will work
        soundMethod("/sounds/airPlane.wav");
        
    }//GEN-LAST:event_logButtonActionPerformed

    private void userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            login();
                if(flag == Constants.FLAG)     // if the login succeed the sound will work
             soundMethod("/sounds/airPlane.wav");
    }//GEN-LAST:event_userKeyPressed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        login();
        if(flag == Constants.FLAG)  // if the login succeed the sound will work         
        soundMethod("/sounds/airPlane.wav");
    }//GEN-LAST:event_passwordFieldKeyPressed


    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginFrame().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton resetButton;
    public javax.swing.JTextField user;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables


}
