/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import core.Agent;
import core.Branch;
import core.Customer;
import core.FlightAttendant;
import core.Pilot;

/**
 *
 * @author Aviad
 */
@SuppressWarnings("serial")
public class ShowChoice extends javax.swing.JDialog {
    //***************************************** Variables *********************************************
    /**MyDesktopPane field*/
    @SuppressWarnings("unused")
	private MyDesktopPane myDesk;
    /**Pilot field*/
    private Pilot pilot;
    /**Agent field*/
    private Agent agent;
    /**FlightAttendant field*/
    private FlightAttendant flightAttendant;
    /**Customer field*/
    private Customer customer;
    
    private Branch branch;
    //**************************************** Constructor ********************************************
    /**
     * Creates new form ShowChoice
     * @param parent 
     * @param modal 
     * @param myDesk 
     * @param object 
     */
    public ShowChoice(java.awt.Frame parent, boolean modal, MyDesktopPane myDesk, Object object) {
        super(parent, modal);
        this.myDesk = myDesk;
        setTitle("Selected Object Details"); //the title of the frame
        initComponents();
        setLocation(465 ,260); // set the Location on screen
        if(object instanceof Pilot){
            pilot = (Pilot) object;
            taChoice.setText(pilot.theString());
        }else if(object instanceof Agent){
            agent = (Agent) object;
            taChoice.setText(agent.theString());
        }else if(object instanceof FlightAttendant){
            flightAttendant = (FlightAttendant) object;
            taChoice.setText(flightAttendant.theString());
        }else if(object instanceof Customer){
            customer = (Customer)object;
            taChoice.setText(customer.theString());
        }else if(object instanceof Branch){
            branch = (Branch)object;
            taChoice.setText(branch.theString());
        }else{
        taChoice.setText(object.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taChoice = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        taChoice.setEditable(false);
        taChoice.setBackground(new java.awt.Color(102, 102, 102));
        taChoice.setColumns(20);
        taChoice.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        taChoice.setRows(5);
        jScrollPane1.setViewportView(taChoice);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taChoice;
    // End of variables declaration//GEN-END:variables
}
